news_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pulse.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

pulse/urls.py
from django.urls import path

from pulse.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topics"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactors"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspapers"
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
]

app_name = "pulse"

pulse/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    def __str__(self):
        return (
            f"{self.username} ({self.years_of_experience} years of experience)"
        )


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField()
    topic = models.ManyToManyField(Topic)
    publishers = models.ManyToManyField(Redactor)

    def __str__(self):
        return self.title

pulse/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth import get_user_model

from pulse.models import Topic, Redactor, Newspaper


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ["name"]


class RedactorForm(UserCreationForm):
    years_of_experience = forms.IntegerField(required=True)

    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
            "email",
        )

    def __init__(self, *args, **kwargs):
        super(RedactorForm, self).__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.instance and self.instance.pk:
            if self.instance.username == username:
                return username
        if Redactor.objects.filter(
                username=username
        ).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError(
                "A user with that username already exists."
            )
        return username

    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data["password1"]:
            user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class NewspaperForm(ModelForm):
    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"
        widgets = {
            "published_date": forms.DateInput(attrs={"type": "date"}),
            "content": forms.Textarea(attrs={"rows": 4, "cols": 40}),
        }


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )
    published_date = forms.DateField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "YYYY-MM-DD"}),
    )
    content = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by content"}),
    )

pulse/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from pulse.models import Topic, Redactor, Newspaper
from pulse.forms import (
    TopicForm,
    RedactorForm,
    NewspaperForm,
    NewspaperSearchForm
)


def index(request: HttpRequest) -> HttpResponse:
    num_topics = Topic.objects.count()
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    context = {
        "num_topics": num_topics,
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
    }
    return render(request, "pulse/index.html", context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "pulse/topic_list.html"
    paginate_by = 5


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    form_class = TopicForm
    template_name = "pulse/topic_form.html"
    success_url = reverse_lazy("pulse:topics")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    form_class = TopicForm
    template_name = "pulse/topic_form.html"
    success_url = reverse_lazy("pulse:topics")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    template_name = "pulse/topic_confirm_delete.html"
    success_url = reverse_lazy("pulse:topics")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    template_name = "pulse/redactor_list.html"
    context_object_name = "redactors"
    paginate_by = 5
    ordering = ["username"]


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    template_name = "pulse/redactor_detail.html"
    context_object_name = "redactor"


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorForm
    success_url = reverse_lazy("pulse:redactors")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorForm
    success_url = reverse_lazy("pulse:redactors")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    template_name = "pulse/redactor_confirm_delete.html"
    success_url = reverse_lazy("pulse:redactors")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    template_name = "pulse/newspaper_list.html"
    context_object_name = "newspaper_list"
    paginate_by = 5
    ordering = ["published_date", "title"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = NewspaperSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by("published_date", "title")
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            if form.cleaned_data.get("title"):
                queryset = queryset.filter(
                    title__icontains=form.cleaned_data["title"]
                )
            if form.cleaned_data.get("published_date"):
                queryset = queryset.filter(
                    published_date=form.cleaned_data["published_date"]
                )
            if form.cleaned_data.get("content"):
                queryset = queryset.filter(
                    content__icontains=form.cleaned_data["content"]
                )
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper
    template_name = "pulse/newspaper_detail.html"


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("pulse:newspapers")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("pulse:newspapers")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    template_name = "pulse/newspaper_confirm_delete.html"
    success_url = reverse_lazy("pulse:newspapers")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newspaper'] = Newspaper.objects.get(pk=self.kwargs['pk'])
        return context

templates/pulse/newspaper_list.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block stylesheets %}
    <!-- Additional CSS for this page -->
{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}
    <header class="header-2">
        <div class="page-header section-height-75 relative"
             style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved11.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 text-center mx-auto">
                        <h1 class="text-white pt-3 mt-n5">Newspaper List</h1>
                        <p class="lead text-white mt-3">Browse our comprehensive list of newspapers</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="pt-3 pb-4" id="count-stats">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                    <div class="d-flex justify-content-between align-items-center">
                        <form action="" method="get" class="form-inline d-flex align-items-center mr-2">
                            {{ search_form|crispy }}
                            <button type="submit" class="btn btn-primary ms-2">
                                <i class="fa fa-search"></i> Search
                            </button>
                        </form>
                        <a class="btn btn-success" href="{% url 'pulse:newspaper-create' %}" style="margin-left: 10px;">Add
                            New Newspaper</a>
                    </div>
                    {% if newspaper_list %}
                        <table class="table mt-3">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Published Date</th>
                                <th>Topics</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for newspaper in newspaper_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'pulse:newspaper-detail' pk=newspaper.id %}">{{ newspaper.id }}</a>
                                    </td>
                                    <td>{{ newspaper.title }}</td>
                                    <td>{{ newspaper.published_date }}</td>
                                    <td>{{ newspaper.topic.all|join:", " }}</td>
                                    <td>
                                        <a href="{% url 'pulse:newspaper-update' pk=newspaper.id %}"
                                           class="btn btn-primary">Edit</a>
                                        <a href="{% url 'pulse:newspaper-delete' pk=newspaper.id %}"
                                           class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% if is_paginated %}
                            <nav aria-label="Page navigation example">
                                <ul class="pagination pagination-primary justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                               aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">&laquo;</span>
                                        </li>
                                    {% endif %}
                                    <li class="page-item active">
                                        <span class="page-link">{{ page_obj.number }} / {{ paginator.num_pages }}</span>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                               aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">&raquo;</span>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    {% else %}
                        <p>No newspapers available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
    <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
{% endblock javascripts %}

templates/pulse/redactor_detail.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block stylesheets %}
    <!-- Additional CSS for this page -->
{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}
    <header class="header-2">
        <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved11.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 text-center mx-auto">
                        <h1 class="text-white pt-3 mt-n5">{{ redactor.username }}</h1>
                        <p class="lead text-white mt-3">Explore the profile of our esteemed redactor.</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="pt-3 pb-4" id="count-stats">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                    <p><strong>Full Name:</strong> {{ redactor.first_name }} {{ redactor.last_name }}</p>
                    <p><strong>Years of Experience:</strong> {{ redactor.years_of_experience }}</p>
                    <p><strong>Email:</strong> {{ redactor.email }}</p>
                    <p><strong>Is staff:</strong> {{ redactor.is_staff|yesno:"Yes,No" }}</p>
                    <div>
                        <h3>Newspapers:</h3>
                        {% if redactor.newspaper_set.all %}
                            {% for newspaper in redactor.newspaper_set.all %}
                                <div>
                                    <p>id: {{ newspaper.id }}</p>
                                    <p><strong>Title:</strong> <a href="{% url 'pulse:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}</a></p>
                                    <p><strong>Published Date:</strong> {{ newspaper.published_date }}</p>
                                    <p><strong>Topics:</strong> {{ newspaper.topic.all|join:", " }}</p>
                                </div>
                                <hr>
                            {% empty %}
                                <p>No Newspapers!</p>
                            {% endfor %}
                        {% else %}
                            <p>No Newspapers!</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block javascripts %}
    <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
{% endblock javascripts %}

templates/pulse/redactor_list.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block stylesheets %}
    <!-- Additional CSS for this page -->
{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}
    <header class="header-2">
        <div class="page-header section-height-75 relative"
             style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved11.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 text-center mx-auto">
                        <h1 class="text-white pt-3 mt-n5">Redactors List</h1>
                        <p class="lead text-white mt-3">Meet our experienced redactors</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="pt-3 pb-4" id="count-stats">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                    <a class="btn btn-success" href="{% url 'pulse:redactor-create' %}" style="margin-bottom: 20px;">Add
                        New Redactor</a>
                    {% if redactors %}
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Years of Experience</th>
                                <th>Email</th>
                                <th>Details</th>
                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for redactor in redactors %}
                                <tr>
                                    <td>{{ redactor.id }}</td>
                                    <td>{{ redactor.username }}</td>
                                    <td>{{ redactor.years_of_experience }}</td>
                                    <td>{{ redactor.email }}</td>
                                    <td><a class="btn btn-info" href="{% url 'pulse:redactor-detail' pk=redactor.id %}">Details</a>
                                    </td>
                                    <td><a class="btn btn-primary"
                                           href="{% url 'pulse:redactor-update' pk=redactor.id %}">Update</a></td>
                                    <td><a class="btn btn-danger"
                                           href="{% url 'pulse:redactor-delete' pk=redactor.id %}">Delete</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% if is_paginated %}
                            <nav aria-label="Page navigation example">
                                <ul class="pagination pagination-primary justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                               aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">&laquo;</span>
                                        </li>
                                    {% endif %}
                                    <li class="page-item active">
                                        <span class="page-link">{{ page_obj.number }} / {{ paginator.num_pages }}</span>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                               aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">&raquo;</span>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    {% else %}
                        <p>No redactors available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block javascripts %}
    <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
{% endblock javascripts %}

templates/pulse/topic_list.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block stylesheets %}
    <!-- Additional CSS for this page -->
{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}
    <header class="header-2">
        <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved11.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 text-center mx-auto">
                        <h1 class="text-white pt-3 mt-n5">Topic List</h1>
                        <p class="lead text-white mt-3">Browse our comprehensive list of topics</p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="pt-3 pb-4" id="count-stats">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                    <a class="btn btn-primary" style="float: right" href="{% url 'pulse:topic-create' %}">Add New Topic</a>
                    {% if topic_list %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for topic in topic_list %}
                                    <tr>
                                        <td>{{ topic.id }}</td>
                                        <td>{{ topic.name }}</td>
                                        <td><a href="{% url 'pulse:topic-update' pk=topic.id %}" class="btn btn-primary">Edit</a></td>
                                        <td><a href="{% url 'pulse:topic-delete' pk=topic.id %}" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <!-- Pagination -->
                        {% if is_paginated %}
                            <nav aria-label="Page navigation example">
                                <ul class="pagination pagination-primary justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item active">
                                        <span class="page-link">{{ page_obj.number }} / {{ paginator.num_pages }}</span>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">&raquo;</span>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    {% else %}
                        <p>No topics available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block javascripts %}
    <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
    <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
{% endblock javascripts %}